### ISSUE TITLE
ASEAG erlaubt keinen Zugriff auf die API

### ISSUE THREAD

**Issue by acmurmeltier69** [acmurmeltier69/Alexa-Busauskunft#13]
Es gibt einen schweren Rückschlag für den Skill.
Auf meine Anfrage bei der ASEAG, ob ich den Namen "ASEAG" für den Skill verwenden darf, bekam ich die Antwort.

_

> "Ich muss Ihnen leider mitteilen, dass Sie diese Daten und die Schnittstelle nicht für Ihre Anwendung nutzen dürfen. Wir haben das – auch mit Blick auf andere Interessenten – grundsätzlich so entschieden."

_

Ich habe nochmal nachgefragt, warum die ASEAG denn eine frei zugängliche API zur Verfügung stellt und deren Benutzung dann nicht erlaubt, habe aber noch keine Antwort erhalten.

**Comment by claell** [comment]
Das ist ja komisch.

Und nervig, dass sich einige Unternehmen gegen tolle Projekte stellen.

**Comment by acmurmeltier69** [comment]
Ich denke ich muss das Projekt offiziell begraben.
Auch nach erneuter Anfrage und Demonstration des Skills (per Video) bleibt die ASEAG bei Ihrerm Verbot der API Benutzung:

>Guten Tag, Herr Kellner,
 >
>ich kann Ihnen auch heute keine andere Antwort geben. Sie dürfen diese Daten und die Schnittstelle nicht nutzen. Das wird – wie schon gesagt – bei uns grundsätzlich so gehandhabt.
Mit freundlichen Grüßen 
Paul Heesel
ASEAG, Aachener Straßenbahn und Energieversorgungs-AG 
Kommunikation und Marke Neuköllner Straße 1, 52068 Aachen

Wirklich sehr schade!
Ich lasse das Github Projekt online. 
Damit kann jeder den Sourcecode verwenden, um die App für andere Verkehrsunternehmen, die weniger restriktiv sind, anzupassen.

**Comment by claell** [comment]
Sehr schade.
Können die das rechtlich gesehen einfach so verbieten? Die Daten sind ja öffentlich abrufbar.

**Comment by acmurmeltier69** [comment]
Da bin ich auch nicht sicher.
Ich kann ja auch nicht eine unverschlüsselte Webseite aufsetzen und dann Benutzern verbieten, sie zu besuchen.
Für das Data Harvesting gibt es spezielle Regeln (über robots.txt), aber das macht der Skill ja nicht.

Interessant ist auch ein Artikel in http://www.ivu.de/fileadmin/ivu/pdf/kundenzeitung/ger/2014/IVU_News_2014_Ausgabe_1.pdf 

Dort heißt es explizit:
>“Auch der VDV hat das Thema Open Data ausführlich diskutiert und rät seinen Mitgliedern in der neuen VDV Mitteilung 7030 zur Vorsicht bei der Veröffentlichung. In Abgrenzung dazu prägt der Verband den Begriff “Open Service”. Diese werden uneingeschränkt befürwortet, Die URA/IVU realtime cloud sind in diesem Sinne Open Services zur Bereitstellung von Echtzeitdaten.“

Ich hab also keine Ahnung, welches Problem die ASEAG hier hat.

Interessant finde ich auch, dass es auf http://ivu.aseag.de/interfaces/ explizites Interfaces gibt wie
SIRI 2.0 Production Timetable Service 
Das legt die Vermutung nahe, dass für ausgewählte 3rd-party Services (z.B. Apple Siri) sogar eigene Interfaces zur Verfügung gestellt werden. Auch Google muss seine ÖPNV Daten ja irgendwo herbekommen.

Hier wird also (finanziert durch Kommunen und Pendler) die Marktdominanz von Monopolisten gestärkt während lokale Innovation unterbunden wird.

**Comment by acmurmeltier69** [comment]
es gibt evtl. Hoffnung.
Scheinbar gibt es andere ÖPNV APIs mit einer breiten Abdeckung die auch Informationen über Aachener Busse enthalten.
Ich habe schon ein paar viel versprechende Links....

**Comment by claell** [comment]
Anscheinend ist die ASEAG da deutlich einschränkender und möchte nicht, dass die Möglichkeiten, die sie von IVU eingekauft hat, auch genutzt werden.

Gut, dass es anscheinend andere APIs gibt, über die man auch an die Daten kommen könnte.

**Comment by flashspys** [comment]
@acmurmeltier69 
Hast du hier mal 'ne Anfrage gestellt?
https://blog.avv.de/uusklamuesert/opendata-fahrplandaten-und-api-schnittstelle-fuer-webentwickler/
