### ISSUE TITLE
Probleme mit <break/> in Fehlermeldungen

### ISSUE THREAD

**Issue by claell** [acmurmeltier69/Alexa-Busauskunft#2]
Bei Fehlermeldungen wird der <break/> tag auf den Karten angezeigt.

Wenn ich zum Beispiel frage, "wann der nächste bus zum blabla", wird eine Fehlermeldung ausgegeben, die aber noch die break tags enthält. Möglicherweise auch ein Fehler von Alexa?

**Comment by acmurmeltier69** [comment]
Nein, da kann Alexa nix dafür.
Aus Faulheit gebe ich die gesprochene Meldung auch in der Card aus.
Es gibt schon eine (bisher leere) Funktion 'DisplaySpeechOutputOnCard' in myask_alexaout, die eigentlich die SSML tags wegmachen soll

**Comment by claell** [comment]
Hm, ich hatte nur gesehen, dass bei

```python
def generalHelp(user_profile):
    speech_prompt = u"Hallo,<break/>"
```

auch ein tag ist, der aber bei mir nicht auf der Karte erscheint. Oder gibt es da einen extra Text, der keinen tag enthält?

**Comment by claell** [comment]
Ah, sehe gerade, dass der "Hallo" String gar nicht mit auf der Karte ist, da wird anscheinend dann der Text von
```python
def DisplayGeneralHelp(user_profile):
```
ausgegeben.

**Comment by acmurmeltier69** [comment]
Ja, normalerweise rufe ich (aus bus_response.py) separate funktionen für Speech (bus_nlg.py NLG = Natural Language Generation) und display (bus_gui.py) auf.
Aber für einfache texte spar ich mir das und kopiere den speech text in die GUI.
Die Funktion DisplaySpeechOutputOnCard() sollte jetzt für diese Fälle eigentlich alle SSML tags rausfiltern.

**Comment by claell** [comment]
Alles klar, dann schließe ich den Issue mal.
