### ISSUE TITLE
Stop Intent funktioniert nicht immer

### ISSUE THREAD

**Issue by claell** [acmurmeltier69/Alexa-Busauskunft#3]
Wenn ich sage "Alexa, frage die ASEAG nach Hilfe" und die Antwort mit "Alexa stopp" unterbreche, werden mir die nächsten Abfahrten angesagt, anstatt den Skill zu beenden.
Das scheint auch sonst zu passieren, vermutlich funktioniert der Stop Intent generell nicht ganz.

**Comment by acmurmeltier69** [comment]
Hm. Ich weiss nicht, ob ich das irgendwie beeinflusen kann. Ich dachte Stopp wird von amazon direkt behandelt. Hast du eine Idee?

**Comment by claell** [comment]
Ah, ich habe gerade mal bei den Intents vom Skill geschaut und man muss glaube ich auch den Stop (und ggf. Cancel Intent) hinzufügen. Also

```json
    {
      "intent": "AMAZON.CancelIntent"
    },
    {
      "intent": "AMAZON.StopIntent"
    }
```

**Comment by acmurmeltier69** [comment]
Oops, das meintest Du. 
Die Handler waren sogar schon drin, nur die intents nicht. Kommt

**Comment by acmurmeltier69** [comment]
sollte jetzt gehen

**Comment by claell** [comment]
Ja, kann ich bestätigen.
