### ISSUE TITLE
Es werden alle Abfahrten ausgegeben, wenn die Linie nicht erkannt wurde

### ISSUE THREAD

**Issue by claell** [acmurmeltier69/Alexa-Busauskunft#4]
Fragt man, wann die Linie 3A fährt, steht bei Buslinie ein "?". Dann werden alle Abfahrten der Haltestelle vorgelesen. Besser wäre es, das abzufangen und eine Meldung auszugeben.

**Comment by acmurmeltier69** [comment]
Ich werde die Linien Eingabe so umbauen, dass auch Worte wie 3A etc erlaubt sind.
EInfach eine Fehlermeldung auszugeben wenn etwas nicht erkannt wird, finde ich aus UX Sicht nicht so gut.
Aber eventuell kann man ja was machen wie "Ich habe die Busnummer nicht erkannt. Hier sind alle Abfahrten ab ...

**Comment by claell** [comment]
Alles klar.

Das Einplanen von Meldungen, falls etwas nicht erkannt wurde, ist aber denke ich schon sinnvoll. Alexa liefert glaube ich teils auch mal ein "?" als Variable, falls es einen Slot nicht passend erkannt hat.

**Comment by acmurmeltier69** [comment]
Ich habe eine neue Version hochgeladen, die dieses Problem beheben sollte.
Alexa gibt eine kurze Fehlermeldung aus und liest dann alle Buslinien vor

**Comment by claell** [comment]
Konnte ich testen, dann schließe ich diesen Issue auch mal.
