### ISSUE TITLE
"Fahrtrichtung" funktioniert nur rudimentär

### ISSUE THREAD

**Issue by acmurmeltier69** [acmurmeltier69/Alexa-Busauskunft#7]
Im Prinzip unterstützt der Skill auch die Ausgabe von Abfahrten nur in eine Richtung (“stadteinwärts”/”stadtauswärts”). 
Allerdings liefert die ASEAG API diese Information momentan leider nicht, obwohl z.B. in der  [API-Dokumentation,](http://content.tfl.gov.uk/tfl-live-bus-river-bus-arrivals-api-documentation.pdf)  ein direction flag vorgesehen ist

Der momentane Filter ist einfach: (aseag_api.MatchesDirection())
 - wenn ein Bus bis Bushof oder Elisenbrunnen fährt ist er "stadteinwärts", sonst "stadtauswärts"
(definiert in aseag_data.HARDCODED_DIRECTIONS)
Es gibt aber natürlich viele Busse, die entweder diese Haltestellen nicht anfahren, oder weiter fahren und deswegen eine andere Endhaltestelle haben.

**Comment by acmurmeltier69** [comment]
Für meine Haltestelle hab ich mir mal die Mühe gemacht, alle Verbindungen nach "inward/outward" zu klassifizieren. (Der Filter erfolgt nach Endhaltestelle, da nur diese in den Verbindungen angegeben ist)

Man könnte das eventuell automatisieren:
 - suche alle Linien, die von einer Haltestelle abfahren und die dazugehörigen Endhaltestellen
 - für jede Linie+Endhaltestelle: Teste, ob der Bus am Bushof stehen bleibt 
    wenn ja, trage diese Endhaltestelle für die Abfahrtsstation als "stadteinwärts" ein

Andere Ideen sind wilkommen

**Comment by claell** [comment]
Generell schwierig, das zu sortieren. Ich finde allein die Definition von stadtein-/auswärts schon schwierig. Bei Aachen zum Glück einigermaßen umsetzbar, da es ein einigermaßen kompaktes Zentrum gibt. Aber Linien wie die 3A/B fahren eher Kreise.

Was mir noch eingefallen ist, wäre sich mal die Netzpläne anzusehen: http://www.aseag.de/fahrplan/netzplaene/
Daraus könnte man (wenn man zu viel Zeit hat) vermutlich aus einem Bereich um das Zentrum ein virtuelles Netz o.ä. erstellen und dann darin einige Haltestellen als Zentrum klassifizieren. Anschließend könnte man jede Linie nachvervolgen und schauen, ab wann ein Bus Richtung der definierten Haltestellen im Zentrum fährt und ab wann er es wieder verlässt (ggf. noch prüfen, dass er nicht gleich wieder ins Zentrum fährt).

Aber im Prinzip braucht man vermutlich gar kein virtuelles Netz, sondern es reicht, wenn man einfach ein paar Haltestellen ungeordnet als Zentrum definiert und dann die Busse nachvervolgt. Also im Prinzip exakt deine Vorgehensweise, nur mit mehreren Haltestellen.

**Comment by feuerrot** [comment]
Ohai!

Ich habe das gleiche Problem schon mal für mein [LED-Panel](https://twitter.com/_pub_feuerrot/status/825705067739222016) gelöst. Ich mache das, indem ich pro Fahrt nochmal die [tripinformation](https://github.com/feuerrot/aseag-python/blob/ledpanel/main#L126) (effektiv: den kompletten Routenverlauf einer einzelnen Verbindung) abrufe und dann [überprüfe](https://github.com/feuerrot/aseag-python/blob/ledpanel/main#L85), ob der Bus zuerst am Bushof oder an meiner Haltestelle vorbeifährt.

Für meinen Anwendungsfall funktioniert das, eigentlich will man sich aber pro Haltestelle eine Menge an weiteren Haltestellen überlegen, die man dann als Einwärts/Auswärts definiert, für alle Haltestellen einmal einen Request machen und dann über die Schnittmenge (via tripid) die Uhrzeiten vergleichen. Das hätte dann den Vorteil, dass man nicht pro Verbindung einen Request absetzt, sondern nur für die eigene und weitere definierte Haltestellen.

**Comment by acmurmeltier69** [comment]
Hallo Feuerrot,
super Idee (und danke, dass du dich hier einklinkst. Deine python API war sozusagen der Anstoß für diesen Skill).
Mit den tripids zu arbeiten ist eine gute Idee!
Ich werd' mal schauen, was ich da machen kann.

**Comment by acmurmeltier69** [comment]
Hm.
Das Problem mit der trpid ist, dass jeder Bus eine andere id hat. 
wenn man die cachen will, muss man eine id für jede Abfahrtszeit speichern :-(
Da ist es doch einfacher, die Möglichen Endhaltestellen zu cachen. Da gibt es pro Linie nur ein paar.

Ich hab mir mal den Netzplan der ASEAG ([link](http://www.aseag.de/fileadmin/user_upload/documents/Netzplaene/Tagnetz_Innenstadt_AC.pdf)) angeschaut und festgestellt: Bis auf die (Ring-)Linien 3A/B und 13A/B fahren alle Busse die in die Innenstadt fahren über Bushof.
Also definiere ich einfach mal 
    "stadteinwärts" = fährt über Bushof
    'stadtauswärts = fährt nicht über Bushof' 
Also brauche ich für jede Haltestelle eine Liste aller Busse (Linie+Endstation), die über den Bushof fahren.
Dazu habe ich ein kleines script "[_collect_inbound.py](https://github.com/acmurmeltier69/Alexa-Busauskunft/blob/master/python/_collect_inbound.py)" gemacht, dass von jeder Haltestelle aus nach (Direkt-)verbindungen* zum Bushof sucht und die gefundenen Linien +Endstationen in einer lookup-Tabelle in [aseag_inbound_connection.py](https://github.com/acmurmeltier69/Alexa-Busauskunft/blob/master/python/aseag_inbound_connection.py) speichert.

Diese wird dann von der Funktion MatchesDirection in aseag_apy benutzt, um festzustellen, ob eine Busverbindung über Bushof geht (=stadteinwärts) oder nicht (=stadtauswärts)

Das Script ist so aufgebaut, dass es bei jedem Aufruf die schon in [aseag_inbound_connection.py](https://github.com/acmurmeltier69/Alexa-Busauskunft/blob/master/python/aseag_inbound_connection.py) gespeicherten "stadteinwärts Verbindungen übernimmt und nur neue Verbindungen dazunimmt.

Wenn man es also ein paar Mal zu unterschiedlichen Tages- und Wochenzeiten laufen lässt, sollte man alle Verbindungen die von irgendeiner Station über Bushof fahren aufgesammelt haben.

Man könnte sehr einfach auch Busse aufnehmen, die nicht direkt zum Bushof fahren.
Aber zu irgendeiner Tageszeit mit Umsteigen dorthin führen
Macht das Sinn?

**Comment by acmurmeltier69** [comment]
OK, ich denke jetzt ist die Liste der Zielhaltestellen stadteinwärts (pro station/linie) einigermaßen stabil.
Um die Ringlinien abzudecken schaue ich wenn es keine Direktverbindung zum Bushof gibt noch, ob die Linie über "Kaiserplatz" fährt und nimmt den dann als "stadteinwärts".
Damit decken wir glaub ich die meisten relevant Fälle ab.
Auch die Asugabe von "3A" und "3B" sollte jetzt gehen. Anfragen kann man die API damit aber nicht.
